### PR TITLE
Fixed bug where non-dFunkt users could not shorten links

### LINKED ISSUE #50: Bug: Internal server error when authorizing user who's not in the dfunkt database
These lines:
https://github.com/datasektionen/pico/blob/master/middlewares.ts#L55-L59
Retrvieves the user's current mandates from dfunkt. If the user does not exist in dfunkt's database (i.e. if the user has neither had a mandate in the chapter nor logged in on the website) dfunkt returns a 404. This is not handled and we just return a 500 without any logs.

dfunkt should probably return an empty array of mandates for unknown users, but pico should arguably not rely on dfunkt to work to allow users to create links.

### PR DESCRIPTION
**Pull request by chopan050**
Closes #50

### CODE REVIEW

File: middlewares.ts [hunk 1]
```diff
@@ -23,47 +23,63 @@ export const authorizePls = async (
...
+
     if (authorizationHeader) {
         token = authorizationHeader.split(" ")[1];
     } else if (req.query.token) {
-        token = req.query.token;
+        token = req.query.token as string;
     }
 
-    if (!token || token.length === 0) {
+    if (token.length === 0) {
```
Comment (elmaxe) [inline middlewares.ts:37]: Possible uncaught error here if token is undefined. Can happen if auth header is a one word string. Can be fixed with `?`

```suggestion
    if (token?.length === 0) {
```

File: middlewares.ts [hunk 2]
```diff
@@ -23,47 +23,63 @@ export const authorizePls = async (
     res: Response,
     next: NextFunction
 ) => {
-    const authorizationHeader = req.headers.authorization;
-    let token;
+    const authorizationHeader: string | undefined = req.headers.authorization;
+    let token = "";
+    let response: AxiosResponse | undefined = undefined;
```
Comment (elmaxe) [inline middlewares.ts:28]: I do not like that you reassign response to use it for both http responses and errors

File: middlewares.ts [hunk 3]
```diff
@@ -23,47 +23,63 @@ export const authorizePls = async (
...
     try {
-        const response = await axios.get(
-            `${configuration.LOGIN_API_URL}/verify/${token}.json?api_key=${configuration.LOGIN_API_KEY}`
-        );
+        url = `${configuration.LOGIN_API_URL}/verify/${token}.json?api_key=${configuration.LOGIN_API_KEY}`;
+        response = await axios.get(url);
+        if (response === undefined) {
+            res.status(500).send("Undefined response");
+            return;
+        }
```
Comment (elmaxe) [inline middlewares.ts:48]:
```suggestion
```

File: middlewares.ts [hunk 4]
```diff
@@ -23,47 +23,63 @@ export const authorizePls = async (
...
-            res.sendStatus(401);
+            res.status(response.status).send(response.data);
+            return;
+        }
+    } catch (err) {
+        response = (err as AxiosError).response;
+        if (response === undefined) {
+            res.status(500).send("Undefined response");
             return;
         }
```
Comment (elmaxe) [inline middlewares.ts:58]: "undefined response" is a strange message to return
```suggestion
```

File: middlewares.ts [hunk 5]
```diff
@@ -72,19 +88,26 @@ export const authorizePls = async (
...
-
-        next();
     } catch (err) {
-        res.sendStatus(500);
-        return;
+        response = (err as AxiosError).response;
+        if (response === undefined) {
+            res.status(500).send("Undefined response");
+            return;
+        }
```
Comment (elmaxe) [inline middlewares.ts:96]:
```suggestion
```

**Review by elmaxe — CHANGES_REQUESTED** [review]

File: middlewares.ts [hunk 6]
```diff
@@ -23,47 +23,63 @@ export const authorizePls = async (
...
+    try {
         // Fetch user's mandates from dfunkt
         // TODO: Cache this
-        const result: CurrentMandate[] = (
-            await axios.get(
-                `https://dfunkt.datasektionen.se/api/user/kthid/${user.user}/current`
-            )
-        ).data.mandates;
-        const mandates = result
+        url = `https://dfunkt.datasektionen.se/api/user/kthid/${user.user}/current`;
```
[the remark this answers is not in the document]
Comment (chopan050) [reply middlewares.ts]: You're right, it was not a good idea in hindsight. I just changed this.

File: middlewares.ts (hunk 1 above)
Comment (chopan050) [reply middlewares.ts]: I didn't think about that case with the auth header. I considered that into the code now.

File: middlewares.ts (hunk 2 above)
Comment (chopan050) [reply middlewares.ts]: Ok, semantically that was a bad idea, so I changed this now.

File: middlewares.ts (hunk 4 above)
Comment (chopan050) [reply middlewares.ts]: Yeah, at that time I didn't really know what to send in that case.
My idea, however, was that if any of the APIs didn't send a response, the Pico server would send a response reporting that error. So I'm not sure if it's a good idea to delete this completely.

I changed the code so that it reflects more accurately what I wanted to convey, following some practices and formatting in the Axios website. The messages should be more descriptive now. I also changed the error code, for I believe that it should instead be 502 instead. The following description seems to match more accurately what I want to communicate to the frontend:
> The 502 Bad Gateway error is an [HTTP status code](https://www.lifewire.com/http-status-codes-2625907) that means that one server on the internet received an invalid response from another server.

What do you think about this change?

File: middlewares.ts [hunk 7]
```diff
@@ -72,19 +94,32 @@ export const authorizePls = async (
...
+            // should proceed normally. Otherwise, return an error.
+            if (status != 404) {
+                res.status(status).send(data);
+                return;
+            }
+        } else {
+            res.status(502).send(
+                "Bad Gateway - No response from the dFunkt API."
+            );
+            return;
```
Comment (mathiasmagnusson) [inline middlewares.ts:111]: The else case here could also mean that `err` was some other error. Perhaps it would be nice to add something like
```js
if (!(err instanceof AxiosError)) {
  console.error(err);
  return res.sendStatus(500);
}
```
at the beginning of the `catch`?

Comment (chopan050) [reply middlewares.ts]: I just made a commit adding your proposal, thanks for pointing this out.

TypeScript wouldn't allow me to use `!(err instanceof AxiosError)`. Apparently `AxiosError` is not a type, but an interface. Luckily they added an `isAxiosError` flag to it, so I used that instead.

To be more consistent with the other error responses, I put the error message in `res.status(500).send(ERROR_MESSAGE)` instead.

**Review by mathiasmagnusson — APPROVED** [review]
Works!
